# ─────────────────────────────────────────────────────────────────────────────
# Verel IaC challenge — "the clean plan that lies"
#
# A small, realistic AWS stack. `terraform plan` shows no literal `0.0.0.0/0` and
# no `Action = "*"` sitting in plain sight. But three changes grant more access
# than intended — each invisible or near-invisible in the *diff*.
#
# Task: find every change that grants more access than intended, BEFORE apply.
# (Answer key in README.md — generated by `verel-ci iac`.)
# ─────────────────────────────────────────────────────────────────────────────

provider "aws" {
  region = "us-east-1"
}

# ── benign cover: a normal app stack ────────────────────────────────────────
resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"
  tags       = { Name = "app-vpc" }
}

resource "aws_security_group" "app" {
  name   = "app-sg"
  vpc_id = aws_vpc.main.id
}

resource "aws_db_instance" "app" {
  identifier          = "app-db"
  engine              = "postgres"
  instance_class      = "db.t3.micro"
  allocated_storage   = 20
  publicly_accessible = false # ← correctly private
  username            = "app"
  password            = var.db_password
  skip_final_snapshot = true
}

resource "aws_s3_bucket" "assets" {
  bucket = "acme-app-assets-prod"
}

resource "aws_s3_bucket_public_access_block" "assets" {
  bucket                  = aws_s3_bucket.assets.id
  block_public_acls       = true # ← all four on: correctly locked down
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_iam_role" "app" {
  name = "app-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "ec2.amazonaws.com" } # ← normal service trust
      Action    = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy" "app_scoped" {
  name = "app-read-assets"
  role = aws_iam_role.app.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = "s3:GetObject" # ← scoped least-privilege
      Resource = "${aws_s3_bucket.assets.arn}/*"
    }]
  })
}

resource "aws_cloudwatch_log_group" "app" {
  name              = "/acme/app"
  retention_in_days = 30
}

# ── planted issue #1: a security-group rule open to the WHOLE internet,
#    written as two halves so a `0.0.0.0/0` search misses it ───────────────────
resource "aws_security_group_rule" "ops_ssh" {
  type              = "ingress"
  from_port         = 22
  to_port           = 22
  protocol          = "tcp"
  security_group_id = aws_security_group.app.id
  cidr_blocks       = ["0.0.0.0/1", "128.0.0.0/1"] # ← together = 0.0.0.0/0
}

# ── planted issue #2: a CI role whose policy is COMPUTED (known after apply),
#    so its blast radius is null in the plan diff ──────────────────────────────
resource "aws_iam_role" "ci" {
  name = "ci-runner"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "codebuild.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
}

# ...200 lines away from where it's attached:
data "aws_iam_policy_document" "ci_permissions" {
  statement {
    effect    = "Allow"
    actions   = ["*"] # ← admin, but rendered "(known after apply)" in the plan
    resources = ["*"]
  }
}

resource "aws_iam_role_policy" "ci" {
  name   = "ci-permissions"
  role   = aws_iam_role.ci.id
  policy = data.aws_iam_policy_document.ci_permissions.json # ← computed
}

# ── planted issue #3: a provisioner that grants admin at apply — a no-op in
#    `resource_changes`; the command lives in the configuration block ──────────
resource "null_resource" "bootstrap" {
  provisioner "local-exec" {
    command = "aws iam attach-role-policy --role-name ci-runner --policy-arn arn:aws:iam::aws:policy/AdministratorAccess"
  }
}

variable "db_password" {
  type      = string
  sensitive = true
}
